### ISSUE TITLE
循环神经网络>嵌入和Word2vec>2.Skip-gram 练习

### ISSUE THREAD

**Issue by Jiuses** [udacity/cn-dlnd-issue-reports#108]
## 课程导航+地址
循环神经网络>嵌入和Word2vec>[2.Skip-gram 练习](https://classroom.udacity.com/nanodegrees/nd101-cn-advanced/parts/3a7742cb-4b38-425b-b53c-d85f8da494c9/modules/9c1e2e43-479b-4747-ad67-505961e7d7e9/lessons/98afa405-585c-4c4d-99aa-1fc6d18161eb/concepts/54a15c96-c67a-4cdf-98b3-ddfb701a5c94#)

## 截图
![2018-08-19 02-25-37](https://user-images.githubusercontent.com/10330600/44302253-6e21ef00-a357-11e8-9bc8-0f6d6751673a.png)

## 具体描述
1. 视频14:24秒，字幕应该将“独热”移到下一个段字幕

**Comment by CheneyZeng** [comment]
@sylviasun916 Thx

**Comment by sylviasun916** [comment]
已修改 感谢反馈
