### ISSUE TITLE
循环神经网络>情绪预测RNN>5.搭建 RNN

### ISSUE THREAD

**Issue by Jiuses** [udacity/cn-dlnd-issue-reports#112]
## 课程导航+地址
循环神经网络>情绪预测RNN>[5.搭建 RNN](https://classroom.udacity.com/nanodegrees/nd101-cn-advanced/parts/3a7742cb-4b38-425b-b53c-d85f8da494c9/modules/9c1e2e43-479b-4747-ad67-505961e7d7e9/lessons/34a24397-2b0f-4c04-9088-1cea220c03b8/concepts/31aa642b-3b60-421e-81cb-b95187e894b3#)

## 截图
![2018-08-19 16-38-26](https://user-images.githubusercontent.com/10330600/44307056-50dc3780-a3ce-11e8-9b5e-18d05febc12c.png)

## 具体描述
1. 视频5:55秒字幕，“使用tf.contrib.rnn.MultiRNNCell”与“Tensorflow令这一切变得简单”的位置应该对调

**Comment by CheneyZeng** [comment]
@sylviasun916 Thx

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
