### ISSUE TITLE
循环神经网络 > 循环神经网络 > [3.循环神经网络的历史]-翻译优化

### ISSUE THREAD

**Issue by sixteentang** [udacity/cn-dlnd-issue-reports#12]
## 课程导航+地址
循环神经网络 > 循环神经网络 > [3.循环神经网络的历史](https://classroom.udacity.com/nanodegrees/nd101-cn-advanced/parts/3a7742cb-4b38-425b-b53c-d85f8da494c9/modules/9c1e2e43-479b-4747-ad67-505961e7d7e9/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/7b7c1680-19e1-46c5-a48a-143ad051254c)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/30287549/43645372-3d3a3b9e-9764-11e8-8fd8-5a0574809b2c.png">

## 具体描述
（1）视频57s处开始的中文字幕“显然这可以让网络具备考虑当前步长以外的优势”，改为“显然这样做的好处是可以让网络不仅仅考虑当前的时间步长”，可能更容易理解。
（2）视频1分50秒处“你也可以在这个视频右侧找到这一话题的更多信息”，其实相关信息是在这个视频下方，这里英文字幕的“right after” 应该理解为“刚好在……之后”而非右侧。建议直接改为“你也可以在这个视频下方找到这一话题的更多信息”

**Comment by CheneyZeng** [comment]
@sylviasun916  Thx

**Comment by sylviasun916** [comment]
已修改，谢谢反馈！
