### ISSUE TITLE
循环神经网络> 循环神经网络 > [5. 前馈神经网络]-翻译优化

### ISSUE THREAD

**Issue by sixteentang** [udacity/cn-dlnd-issue-reports#13]
## 课程导航+地址
循环神经网络> 循环神经网络 > [5. 前馈神经网络](https://classroom.udacity.com/nanodegrees/nd101-cn-advanced/parts/3a7742cb-4b38-425b-b53c-d85f8da494c9/modules/9c1e2e43-479b-4747-ad67-505961e7d7e9/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/ebec6246-752c-49ef-bf74-423b8c3683f3)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/30287549/43647142-58f14814-9769-11e8-8dde-0dbd1dccd13d.png">

## 具体描述
（1）第一个视频2分4秒处中文字幕“通过这种方式我们得到一个输入x找到新的输出y”，可否改为“这样当给我们一个新的输入x时，我们能够通过这个函数算出对应的新的输出y” 
（2）第一个视频4分23秒处中文字幕“概括训练集的网络”是否可译为“一个不仅仅能够泛化训练集的网络”
（3）第二个视频1分43秒处中文字幕有“需要训练这个王座”，应改为“需要训练这个网络”

**Comment by CheneyZeng** [comment]
@sylviasun916 Thx

**Comment by sylviasun916** [comment]
已修改，感谢反馈！
