### ISSUE TITLE
Trouble in fast-style-transfer

### ISSUE THREAD

**Issue by lululily** [udacity/cn-dlnd-issue-reports#2]

**Comment by caochenwei** [comment]
请问具体是？

**Comment by lululily** [comment]
lesson web link:

https://classroom.udacity.com/nanodegrees/nd101/parts/f728a40e-b1b7-4c25-b813-09d524bf0c98/modules/1ecd1d84-5e46-4665-a44c-b37c43118bf3/lessons/0273757e-bd54-42b2-a099-2d9d8c6fb999/concepts/7991da18-bbd0-4606-83e5-3bc5ce558e70

在这一课中我按文档中的文件搭建了环境和建立了文件夹，并按命令的格式输入了命令，但是运行结果并不正确

**Comment by caochenwei** [comment]
可以把你的问题发在深度学习论坛吗？助教会回答这类技术问题。
https://discussions.youdaxue.com/c/dlnd-nn

我们这里主要是翻译和内容报错～
