### ISSUE TITLE
深度强化学习 > 强化学习框架：问题 > [14. MDP 第2部分]

### ISSUE THREAD

**Issue by haofrank** [udacity/cn-dlnd-issue-reports#22]
## 课程导航+地址
深度强化学习 > 强化学习框架：问题 > [14. MDP 第2部分](https://classroom.udacity.com/nanodegrees/nd101-cn-advanced/parts/5a8c821d-84e8-46d9-9d12-a4532009d994/modules/2437007f-86ec-42bc-9975-991c3a3f665b/lessons/86acfc34-0551-4cc6-8de4-a1ab2e66b5af/concepts/6462cdf5-fa3f-435f-82c9-f3271ec404ac)

## 截图
![image](https://user-images.githubusercontent.com/18546749/43678793-5fddda14-984c-11e8-8573-3061affaf538.png)

## 具体描述
视频00:35处缺少字幕翻译

**Comment by CheneyZeng** [comment]
@sylviasun916 Thx

**Comment by sylviasun916** [comment]
已补全  是字幕格式问题，已修改好，感谢反馈！
