### ISSUE TITLE
【在TensorFlow 中的卷积神经网络>>>>TensorFlow 卷积层】链接有效性

### ISSUE THREAD

**Issue by wudiudiu07** [udacity/cn-dlnd-issue-reports#32]
## 课程导航+地址
在TensorFlow 中的卷积神经网络>>>>TensorFlow 卷积层

## 具体描述
tf.nn.bias_add() 函数对矩阵的最后一维加了偏置项
tf.nn.conv2d() 函数来计算卷积
上面两个函数链接打不开【开了vpn也不行】
建议测试一下有效性

**Comment by wudiudiu07** [comment]
试了一下www.tensorflow.org为前缀的网站都打不开

**Comment by CheneyZeng** [comment]
我们已经全部都改为国内镜像啦～
