### ISSUE TITLE
卷积神经网络 > keras实现卷积神经网络> 2.CNN的应用 Go翻译错误

### ISSUE THREAD

**Issue by brucehe3** [udacity/cn-dlnd-issue-reports#39]
## 课程导航+地址
例子：卷积神经网络 > keras实现卷积神经网络> [2.CNN的应用](https://classroom.udacity.com/nanodegrees/nd101-cn-advanced/parts/5fb0432c-7428-4687-8a05-87475d58a6ec/modules/29a64a22-b559-4853-af3f-f7d5f0038c0f/lessons/37492b45-ee34-4dc3-a2e8-076149f92562/concepts/e7190f8c-c824-4936-89ff-db6230fd3d12)

## 截图
![image](https://user-images.githubusercontent.com/6733523/43784541-f1419652-9a96-11e8-92ba-de2f4c03dcc4.png)

## 具体描述
视频2:21s处字幕 Go，围棋的英文翻译就是Go（源自日文）

**Comment by CheneyZeng** [comment]
@sylviasun916 Thx

**Comment by sylviasun916** [comment]
已修改，感谢反馈！
