### ISSUE TITLE
视频内容未翻译

### ISSUE THREAD

**Issue by JaimeTang** [udacity/cn-dlnd-issue-reports#4]
## 课程导航+地址
Neural Networks > Introduction to Neural Networks > Perceptron Algorithm
(https://classroom.udacity.com/nanodegrees/nd101-cn-advanced/parts/d0e8d7b2-a9bc-4eb2-b76e-bee3874c92a5/modules/e6a4e4a1-98a9-4afe-a744-7ae6a59c01b8/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/dc837952-c0d8-43fc-921c-f1ffe316c795)

## 截图
![image](https://user-images.githubusercontent.com/22786828/42145989-3ca4a4ca-7df7-11e8-8395-144434ba2a1b.png)

## 具体描述
视频内容未翻译

**Comment by CheneyZeng** [comment]
中文版是有字幕的哦～
