### ISSUE TITLE
深度强化学习 > 强化学习框架：解决方案 >  [9. 动作值函数]

### ISSUE THREAD

**Issue by haofrank** [udacity/cn-dlnd-issue-reports#41]
## 课程导航+地址
深度强化学习 > 强化学习框架：解决方案 >  [9. 动作值函数](https://classroom.udacity.com/nanodegrees/nd101-cn-advanced/parts/5a8c821d-84e8-46d9-9d12-a4532009d994/modules/2437007f-86ec-42bc-9975-991c3a3f665b/lessons/ce8d7dbc-3320-4440-bdd3-556b8ca3fda2/concepts/e01d0ddc-54ab-4a87-90af-bf759c6d6df1)

## 截图
![image](https://user-images.githubusercontent.com/18546749/43790058-1d6ed214-9aa4-11e8-8890-d948d9515ff4.png)

## 具体描述
视频00:52s字幕建议**提前0.5秒**，这样就和视频讲解的内容一至了，不然容易产生疑惑。。

**Comment by CheneyZeng** [comment]
@sylviasun916 Thx

**Comment by sylviasun916** [comment]
已修改，感谢反馈！
