### ISSUE TITLE
字幕翻译问题

### ISSUE THREAD

**Issue by JaimeTang** [udacity/cn-dlnd-issue-reports#5]
## 课程导航+地址
Neural Networks > Introduction to Neural Networks > Perceptron Trick
(https://classroom.udacity.com/nanodegrees/nd101-cn-advanced/parts/d0e8d7b2-a9bc-4eb2-b76e-bee3874c92a5/modules/e6a4e4a1-98a9-4afe-a744-7ae6a59c01b8/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/8ea20904-0215-4e44-afa9-bb5a720bd028)

## 截图
![image](https://user-images.githubusercontent.com/22786828/42146182-cf66d5a2-7df8-11e8-89d5-0f8fc12c4e4f.png)

## 具体描述
0.57s，“bias unti”应当翻译成“偏置单元”

**Comment by CheneyZeng** [comment]
@sylviasun916

**Comment by sylviasun916** [comment]
已修改，谢谢反馈！
