### ISSUE TITLE
循环神经网络> 情绪预测RNN > [5.搭建RNN]-翻译准确性

### ISSUE THREAD

**Issue by sixteentang** [udacity/cn-dlnd-issue-reports#51]
## 课程导航+地址
循环神经网络> 情绪预测RNN > [5.搭建RNN](https://classroom.udacity.com/nanodegrees/nd101-cn-advanced/parts/3a7742cb-4b38-425b-b53c-d85f8da494c9/modules/9c1e2e43-479b-4747-ad67-505961e7d7e9/lessons/34a24397-2b0f-4c04-9088-1cea220c03b8/concepts/31aa642b-3b60-421e-81cb-b95187e894b3)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/30287549/43838000-c805e76e-9b4c-11e8-98f2-0cf94ed01519.png">

## 具体描述
视频6分5s处单词“cell”，译为“单元”是否比译为“细胞”更好，这个词后面多次出现（6分27秒，6分33秒，6分37秒，6分45秒，6分49秒，6分51秒，6分56秒，8分34秒，8分47秒）都译为了“细胞”，这里并非生物学场景，如非惯例称谓还是译为“单元”更好些（而且本课下一小节的视频就译为了“单元”）。

**Comment by CheneyZeng** [comment]
@sylviasun916 Thx

**Comment by sylviasun916** [comment]
已修改，感谢反馈！
