### ISSUE TITLE
生成对抗网络 > 生成对抗网络 > [11. 构建网络]-字幕问题

### ISSUE THREAD

**Issue by sixteentang** [udacity/cn-dlnd-issue-reports#61]
## 课程导航+地址
生成对抗网络 > 生成对抗网络 > [11. 构建网络](https://classroom.udacity.com/nanodegrees/nd101-cn-advanced/parts/34ed075b-3ca2-45f0-916c-00db3186f18f/modules/af4b44d7-35bd-4408-bf77-22e469eec31b/lessons/61a406ec-8720-4a70-a0c0-2e5086131698/concepts/1a8b547d-49fc-46d3-a3d8-8507e0997428)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/30287549/44001720-831c1496-9e69-11e8-9f79-08899288b117.png">

## 具体描述
视频1分29秒处，英文字幕这里有一个单词漏听用[INAUDIBLE]代替了，对应的中文字幕也是用[?]代替，这里联系课程上下文的内容和发音，这个漏听的单词应该是tanh函数的“tanh”。

**Comment by CheneyZeng** [comment]
@sylviasun916 Thx!

**Comment by sylviasun916** [comment]
已修改，感谢反馈！
