### ISSUE TITLE
生成对抗网络 >半监督学习 > [4. 准备数据]-翻译优化

### ISSUE THREAD

**Issue by sixteentang** [udacity/cn-dlnd-issue-reports#70]
## 课程导航+地址
生成对抗网络 >半监督学习 > [4. 准备数据](https://classroom.udacity.com/nanodegrees/nd101-cn-advanced/parts/34ed075b-3ca2-45f0-916c-00db3186f18f/modules/af4b44d7-35bd-4408-bf77-22e469eec31b/lessons/1411d674-356f-4a26-961e-bc04a059f36e/concepts/93ae8a83-4638-4d54-9679-27da459322b7)

## 截图
无

## 具体描述
视频59s处‘the validation set’（后面又出现了几次），这里中文字幕翻译为“校验数据集”，按机器学习一般的约定俗成的翻译法，一般译为“验证数据集”。

**Comment by CheneyZeng** [comment]
@sylviasun916 Thx

**Comment by sylviasun916** [comment]
已修改，谢谢反馈！
