### ISSUE TITLE
深度强化学习>强化学习框架：问题> 14. MDP（第2部分）

### ISSUE THREAD

**Issue by OLOIUO** [udacity/cn-dlnd-issue-reports#76]
## 课程导航+地址
例子：深度强化学习> 强化学习框架：问题 > [14. MDP（第2部分）](https://classroom.udacity.com/nanodegrees/nd101-cn-advanced/parts/5a8c821d-84e8-46d9-9d12-a4532009d994/modules/2437007f-86ec-42bc-9975-991c3a3f665b/lessons/86acfc34-0551-4cc6-8de4-a1ab2e66b5af/concepts/6462cdf5-fa3f-435f-82c9-f3271ec404ac#)

## 截图
<
![image](https://user-images.githubusercontent.com/39209985/44192846-83362c80-a163-11e8-9dc0-5eae007debac.png)
>

## 具体描述
视频4m19s处字幕电量很高，需改为电量很低

**Comment by CheneyZeng** [comment]
@sylviasun916  thx

**Comment by sylviasun916** [comment]
已修改，感谢反馈！
