### ISSUE TITLE
循环神经网络>循环神经网络>循环神经网络(第二部分)

### ISSUE THREAD

**Issue by Jiuses** [udacity/cn-dlnd-issue-reports#96]
## 课程导航+地址
循环神经网络>循环神经网络>[循环神经网络(第二部分)](https://classroom.udacity.com/nanodegrees/nd101-cn-advanced/parts/3a7742cb-4b38-425b-b53c-d85f8da494c9/modules/9c1e2e43-479b-4747-ad67-505961e7d7e9/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/37e5c026-5ec4-44ef-b3c8-ceb1c1532b8f#)

## 截图
![2018-08-18 16-25-09](https://user-images.githubusercontent.com/10330600/44297396-4a34be00-a303-11e8-9c3d-cae7f98d0c58.png)

## 具体描述
1. 视频2:25秒，字幕翻译错误
2. 视频2:46秒，字幕语音对不上
3. 视频3:07秒，字幕语音对不上
4. 视频2:25秒，字幕翻译错误, "存储"翻译不妥

**Comment by CheneyZeng** [comment]
@sylviasun916 只要是1的错误

**Comment by CheneyZeng** [comment]
视频2:25秒，改成“我们只需要输入，以及连接输入和隐藏层的权重”。
@sylviasun916 圆圆你教我如何改字幕吧，我不知道去哪个repo去找。。。感谢

**Comment by sylviasun916** [comment]
已修改！感谢反馈！

@CheneyZeng Rita 我已修改啦，谢谢！ 嗯嗯好呀，找时间我们可以过一下怎么改字幕哦！谢谢 Rita!
